// src/pages/register.tsx
import SEO from "@/components/seo";
import Layout from "@/components/layout";
import {
  Box,
  Button,
  Checkbox,
  Container,
  Flex,
  FormControl,
  FormLabel,
  Heading,
  Input,
  Stack,
  Text,
  useColorModeValue,
} from "@chakra-ui/react";
import NextLink from "next/link";
import { useRouter } from "next/router";
import { FormEvent, useEffect, useState } from "react";
import { useRecoilState } from "recoil";
import { clientStore, tokenStore } from "@/utils/stores";
import Navbar from "@/components/navbar";

const Register = () => {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [terms, setTerms] = useState(false);
  const [error, setError] = useState<
    {
      code: string;
      message: string;
    }[]
  >([]);
  const [client] = useRecoilState(clientStore);
  const [token, setToken] = useRecoilState(tokenStore);

  useEffect(() => {
    router.prefetch("/app");
    router.prefetch("/reset-password");
    router.prefetch("/login");

    if (token) {
      router.push("/app");
    }
  }, [router, token]);

  const register = async (
    event: FormEvent<HTMLFormElement> & {
      target: {
        email: {
          value: string;
        };
        password: {
          value: string;
        };
        username: {
          value: string;
        };
        confirmpassword: {
          value: string;
        };
      };
    },
  ) => {
    event.preventDefault();
    setLoading(true);
    setError([]);

    const username = event.target.username.value;
    const email = event.target.email.value;
    const password = event.target.password.value;
    const confirmPassword = event.target.confirmpassword.value;

    if (password !== confirmPassword) {
      setError([
        { code: "PASSWORDS_DO_NOT_MATCH", message: "Passwords do not match." },
      ]);

      setLoading(false);
    }

    // Testing against the regexes (which should be the same that the backend uses) helps prevent unnecessary requests.
    if (!client.EmailRegex.test(email)) {
      setError([{ code: "INVALID_EMAIL", message: "Invalid email." }]);
      setLoading(false);

      return;
    }

    if (!client.PasswordRegex.test(password)) {
      setError([{ code: "INVALID_PASSWORD", message: "Invalid password." }]);
      setLoading(false);

      return;
    }

    if (!terms) {
      setError([
        {
          code: "TERMS_NOT_ACCEPTED",
          message: "You must accept the terms of service.",
        },
      ]);
      setLoading(false);

      return;
    }

    const registeredAccount = await client.registerAccount({
      email,
      password,
      username,
      resetClient: true,
    });

    if (!registeredAccount) {
      setError([{ code: "UNKNOWN", message: "Unknown error occurred." }]);
      setLoading(false);

      return;
    }

    if (registeredAccount.success) {
      setToken(registeredAccount.token);

      client.connect();

      router.push("/app");

      return;
    }

    if (registeredAccount.errors.email || registeredAccount.errors.password) {
      setError([
        {
          code: "INVALID_EMAIL_PASSWORD",
          message: "Invalid Email and or Password",
        },
      ]);
    } else if (registeredAccount.errors.username) {
      setError([
        {
          code: "INVALID_USERNAME",
          message: "Invalid Username (This username may be maxed out)",
        },
      ]);
    } else if (registeredAccount.errors.unknown) {
      setError([
        {
          code: "UNKNOWN",
          message: `${Object.entries(registeredAccount.errors.unknown).map(
            ([k, obj]) => `${k} - ${obj.Message}`,
          )}`,
        },
      ]);
    } else {
      setError([{ code: "UNKNOWN", message: "Unknown error occurred." }]);
    }

    setLoading(false);
  };

  return (
    <>
      <SEO title={"Register"} description={""} />
      <Navbar />
      <Layout>
        <form onSubmit={register}>
          {/* @ts-expect-error -- (no clue what the issue is here) */}
          <Box align={"center"} justify={"center"} position={"relative"}>
            {/* @ts-expect-error -- (no clue what the issue is here) */}
            <Container maxW={"7xl"} columns={{ base: 1, md: 2 }}>
              <>
                <Heading
                  lineHeight={1.1}
                  fontSize={{ base: "3xl", sm: "4xl", md: "5xl", lg: "6xl" }}
                >
                  Register for{" "}
                  <Text
                    as={"span"}
                    bgGradient="linear(to-r, red.400,pink.400)"
                    bgClip="text"
                  >
                    Kastel!
                  </Text>
                </Heading>

                <br />

                <Box
                  mt={5}
                  bg={useColorModeValue("gray.100", "gray.700")}
                  rounded={"xl"}
                  p={{ base: 4, sm: 6, md: 8 }}
                  // @ts-expect-error -- (no clue what the issue is here)
                  spacing={{ base: 8 }}
                  maxW={{ lg: "lg" }}
                >
                  <Box mt={5}>
                    <Stack spacing={4}>
                      {error.length > 0 && (
                        <Text
                          mt={-3}
                          as={"span"}
                          bgGradient="linear(to-r, red.400,pink.400)"
                          bgClip="text"
                        >
                          {error.map((err) => {
                            return err.message;
                          })}
                        </Text>
                      )}

                      <FormControl id="username">
                        <FormLabel>Username</FormLabel>
                        <Input
                          id={"username"}
                          required={true}
                          type={"text"}
                          placeholder={"Cool User"}
                          bg={useColorModeValue("gray.200", "gray.600")}
                          border={0}
                          color={useColorModeValue("gray.900", "gray.100")}
                          _placeholder={{
                            color: useColorModeValue("gray.500", "gray.100"),
                          }}
                        />
                      </FormControl>

                      <FormControl id="email">
                        <FormLabel>Your Email</FormLabel>
                        <Input
                          id={"email"}
                          required={true}
                          type={"email"}
                          placeholder={"hello@example.com"}
                          bg={useColorModeValue("gray.200", "gray.600")}
                          border={0}
                          color={useColorModeValue("gray.900", "gray.100")}
                          _placeholder={{
                            color: useColorModeValue("gray.500", "gray.100"),
                          }}
                        />
                      </FormControl>

                      <FormControl id="password">
                        <FormLabel>Password</FormLabel>
                        <Input
                          id={"password"}
                          required={true}
                          type={"password"}
                          placeholder={"••••••••"}
                          bg={useColorModeValue("gray.200", "gray.600")}
                          border={0}
                          color={useColorModeValue("gray.900", "gray.100")}
                          _placeholder={{
                            color: useColorModeValue("gray.500", "gray.100"),
                          }}
                        />
                      </FormControl>

                      <FormControl id="confirmpassword">
                        <FormLabel>Confirm Password</FormLabel>
                        <Input
                          id={"confirmpassword"}
                          required={true}
                          type={"password"}
                          placeholder={"••••••••"}
                          bg={useColorModeValue("gray.200", "gray.600")}
                          border={0}
                          color={useColorModeValue("gray.900", "gray.100")}
                          _placeholder={{
                            color: useColorModeValue("gray.500", "gray.100"),
                          }}
                        />
                      </FormControl>

                      <Flex>
                        <Checkbox onChange={() => setTerms(!terms)}>
                          I agree to the Terms and Conditions
                        </Checkbox>
                      </Flex>
                    </Stack>

                    {loading ? (
                      <Button
                        isLoading
                        fontFamily={"heading"}
                        mt={8}
                        w={"full"}
                        _hover={{
                          bgGradient: "linear(to-r, red.400,pink.400)",
                          boxShadow: "xl",
                        }}
                        bgGradient="linear(to-r, red.400,pink.400)"
                        color={"white"}
                      >
                        Submitting
                      </Button>
                    ) : (
                      <Button
                        type={"submit"}
                        fontFamily={"heading"}
                        mt={8}
                        w={"full"}
                        _hover={{
                          bgGradient: "linear(to-r, red.400,pink.400)",
                          boxShadow: "xl",
                        }}
                        bgGradient="linear(to-r, red.400,pink.400)"
                        color={"white"}
                      >
                        Submit
                      </Button>
                    )}

                    <Stack
                      justify={"center"}
                      mt={2}
                      direction={["column", "row"]}
                    >
                      <NextLink prefetch={false} href={"/login"}>
                        <Button
                          fontFamily={"heading"}
                          w={"full"}
                          bgGradient="linear(to-r, red.400,pink.400)"
                          color={"white"}
                          _hover={{
                            bgGradient: "linear(to-r, red.400,pink.400)",
                            boxShadow: "xl",
                          }}
                        >
                          Have an Account?
                        </Button>
                      </NextLink>

                      <NextLink prefetch={false} href={"/reset-password"}>
                        <Button
                          fontFamily={"heading"}
                          w={"full"}
                          bgGradient="linear(to-r, red.400,pink.400)"
                          color={"white"}
                          _hover={{
                            bgGradient: "linear(to-r, red.400,pink.400)",
                            boxShadow: "xl",
                          }}
                        >
                          Forgot Password?
                        </Button>
                      </NextLink>
                    </Stack>
                  </Box>
                </Box>
              </>
            </Container>
          </Box>
        </form>
      </Layout>
    </>
  );
};

export default Register;

// src/routes/register/+page.svelte
<script>
    import {browser} from '$app/environment';
    import {initClient} from '$lib/client';
    import {fade} from 'svelte/transition';
    import {ready, token} from '$lib/stores.js';
    import {t} from '$lib/translations';
    import {goto} from '$app/navigation';

    /**
     * @type {import('@kastelll/wrapper').Client}
     */
    let client;

    // eslint-disable-next-line no-unused-vars
    ready.subscribe((value) => {
        if ($token) {
            if (browser) {
                goto('/app');
            }
        } else {
            client = initClient();
        }
    });

    let error = {
        message: 'Invalid email or password',
        shown: false
    };

    // eslint-disable-next-line no-unused-vars
    function onSubmit(e) {
        const username = e.target[0].value;
        const email = e.target[1].value;
        const password = e.target[2].value;
        const confirmPassword = e.target[3].value;
        const terms = e.target[4].checked;

        if (password !== confirmPassword) {
            error = {
                message: 'Passwords do not match',
                shown: true
            };
            return;
        }

        if (!terms) {
            error = {
                message: 'You must accept the terms and conditions',
                shown: true
            };
            return;
        }

        client.registerAccount({email, password, username, resetClient: true}).then((data) => {
            if (data.success) {
                token.set(data.token);

                client.connect();

                goto('/app');

                return;
            }

            for (const [key, value] of Object.entries(data.errors)) {
                if (value) {
                    error.message = `${error.message === 'N/A' ? '' : error.message}\n${key} is invalid`;
                }
            }

            if (error.message !== 'N/A') {
                error.shown = true;

            } else {
                error.message = 'Unknown error, please try again later';
                error.shown = true;
            }
        });

    }
</script>

<div class="inset-0 flex items-center justify-center w-full splash">
    <br/>
    <section out:fade={{ duration: 200 }}>
        <div class="mt-5 mb-5 flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
            <p class="mb-5 font-sans text-6xl font-bold text-left text-white/[0.92]">
                Register for Kastel!
            </p>
            <div class="w-full rounded-lg shadow md:mt-0 sm:max-w-md xl:p-0 bg-[#2d3748]">
                <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                    {#if error.shown}
                        <div class="bg-red-500 text-white p-2 rounded-lg">
                            {error.message}
                        </div>
                    {/if}
                    <form class="space-y-4 md:space-y-6" on:submit|preventDefault={onSubmit}>
                        <div>
                            <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                                   for="username">{$t('common.username')}</label>
                            <input class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                   id="username" name="username"
                                   required
                                   type="text">
                        </div>
                        <div>
                            <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                                   for="email">{$t('common.email')}</label>
                            <input class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                   id="email" name="email"
                                   required
                                   type="email">
                        </div>
                        <div>
                            <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                                   for="password">{$t('common.password')}</label>
                            <input class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                   id="password" name="password" placeholder="••••••••"
                                   required
                                   type="password">
                        </div>
                        <div>
                            <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                                   for="confirm-password">{$t('common.confirmPass')}</label>
                            <input class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                   id="confirm-password" name="confirm-password" placeholder="••••••••"
                                   required
                                   type="password">
                        </div>
                        <div class="flex items-start">
                            <div class="flex items-center h-5">
                                <input aria-describedby="terms"
                                       class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600 dark:ring-offset-gray-800"
                                       id="terms"
                                       required
                                       type="checkbox">
                            </div>
                            <div class="ml-3 text-sm">
                                <label class="font-light text-gray-500 dark:text-gray-300" for="terms">I accept the <a
                                        class="font-medium text-primary-600 hover:underline dark:text-primary-500"
                                        href="/terms">Terms and Conditions</a></label>
                            </div>
                        </div>
                        <button class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
                                type="submit">
                            Create an account
                        </button>
                        <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                            Already have an account? <a
                                class="font-medium text-primary-600 hover:underline dark:text-primary-500"
                                href="/login">Login
                            here</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <br/><br/>
</div>

<style>
    .splash {
        background-image: url('/splash.svg');
        background-repeat: no-repeat;
        background-position: center;
        background-size: cover;
        background-color: #161922;
    }
</style>
